spring.application.name=budget-manager

# Database configuration
# Use DB_URL environment variable in production; fall back to H2 in-memory for local dev
spring.datasource.url=${DB_URL:jdbc:h2:mem:budgetdb}
spring.jpa.hibernate.ddl-auto=update

# Using .env file hosted in the root directory of the project and using in intellij idea
# should change this to environment variables in containerized environment
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.show-sql=true
