spring.application.name=budget-manager

# Database configuration
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

#uing .env file hosted in the root directory of the project and using in intellij idea
#should change this to environment variables in containerized environment
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}